version: "3"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    networks:
      - postgres-network

  metabase:
    image: metabase/metabase
    restart: always
    volumes:
      - "./metabase_data:/metabase-data"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin
      MB_DB_HOST: db
    ports:
      - 3000:3000
    depends_on: 
      - db
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge